# Generated by Django 4.0 on 2021-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='/static/public/images/icons8-person-64.png', upload_to='images/'),
        ),
    ]
