# Generated by Django 4.0 on 2021-12-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_car_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='car',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
