# Generated by Django 4.0 on 2021-12-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_rename_number_mobile_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='phone_number',
        ),
    ]
