# Generated by Django 4.0 on 2021-12-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_rename_number_phone_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fax',
            old_name='number',
            new_name='fax_number',
        ),
    ]
