# Generated by Django 4.0 on 2021-12-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_rename_number_fax_fax_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='address',
            new_name='social_address',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='social_name',
        ),
    ]
